# Generated by Django 4.1 on 2024-04-18 10:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="score",
        ),
    ]
